name: Build Ryujinx Launcher

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: RyujinxLauncher.exe
            upload_name: RyujinxLauncher-Windows
            sep: ';'
            icon: 'assets\RyujinxLauncherIcon.ico'
          
          - os: ubuntu-latest
            artifact_name: RyujinxLauncher
            upload_name: RyujinxLauncher-Linux
            sep: ':'
            icon: 'assets/RyujinxLauncherPNG.png'
            
          - os: macos-latest
            artifact_name: RyujinxLauncher
            upload_name: RyujinxLauncher-MacOS
            sep: ':'
            icon: 'assets/RyujinxLauncherIcon.icns'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Linux specific: Install SDL2 dev headers
    - name: Install SDL2 (Linux Only)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

    # Build the application
    - name: Build with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --name "RyujinxLauncher" --icon="${{ matrix.icon }}" --add-data "assets${{ matrix.sep }}assets" src/RyujinxLauncher.py

    # Set Permission (Linux/MacOS)
    # We apply this to the raw binary so GitHub preserves it in the auto-zip
    - name: Set Permissions (Unix)
      if: runner.os != 'Windows'
      run: chmod +x dist/${{ matrix.artifact_name }}

    # Upload the Raw Binary
    # GitHub Actions will automatically ZIP this into 'upload_name.zip'
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.upload_name }}
        path: dist/${{ matrix.artifact_name }}